name: Deploy Julallim Front Server

on:
    push:
        branches: [ develop ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: Build React app
              run: npm run build

            - name: Add SSH key
              run: |
                echo "${{ secrets.SSH_KEY }}" > id_rsa
                chmod 600 id_rsa
                eval "$(ssh-agent -s)"
                ssh-add id_rsa

            - name: Build Docker image
              run: |
                echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV  # BuildKit 활성화
                docker build --no-cache -t julallim_front .  # 현재 디렉토리에서 빌드

            - name: Save Docker image as tar
              run: docker save -o julallim_front.tar julallim_front

            - name: Copy Docker image to EC2
              uses: appleboy/scp-action@v0.1.0
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.SSH_KEY }}
                port: 22
                source: "julallim_front.tar"
                target: "/home/ubuntu/"

            - name: Execute remote commands via SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.SSH_KEY }}
                port: 22
                script: |
                    # Docker 이미지 로드 및 컨테이너 실행
                    docker load -i /home/ubuntu/julallim_front.tar
                    docker-compose down
                    docker-compose up -d
                    sudo docker image prune -f
